#!/bin/sh
#
# shellcheck shell=dash

refname=$1
oldrev=$2
newrev=$3
# Unused variables (commented out for clarity/shellcheck).
#oldtree=$4
#newtree=$5
#access_flag=$6
#refex=$7
#repo=$8

reject()
{
	echo "================================================================"
	echo "$1"
	echo "================================================================"
	exit 1
}

readonly STABLE13_HEAD_REF="refs/heads/stable/13"
readonly STABLE14_HEAD_REF="refs/heads/stable/14"
readonly STABLE15_HEAD_REF="refs/heads/stable/15"

openzfs_merge_ok() {
	local branch_src="${1}"
	local branch_dst="${2}"

	local rc=1

	case "${branch_src#refs/heads/vendor/openzfs/}" in
	zfs-2.1-release)
		[ "${branch_dst}" = "${STABLE13_HEAD_REF}" ] && rc=0
		;;
	zfs-2.2-release)
		[ "${branch_dst}" = "${STABLE14_HEAD_REF}" ] && rc=0
		;;
	zfs-2.4-release)
		[ "${branch_dst}" = "${STABLE15_HEAD_REF}" ] && rc=0
		;;
	*)
		;;
	esac
	return "${rc}"
}

for rev in $(git log --format=%H "${oldrev}..${newrev}" 2>/dev/null); do
	p2=$(git log -1 --format=%P "${rev}" | awk '{print $2}')
	# if this is a merge commit
	if [ -n "${p2}" ]; then
		branch_src=$(git branch --contains "${p2}" | grep '^  vendor/')
		branch_dst=${refname}

		if [ -z "${branch_src}" ]; then
			reject "Currently only allow merge from vendor/*"
		else
			branch_src="refs/heads/${branch_src##  }"
		fi

		if [ "${branch_dst}" = "refs/heads/main" ]; then
			exit 0
		fi

		case "${branch_src}" in
		refs/heads/vendor/openzfs/*)
			openzfs_merge_ok "${branch_src}" "${branch_dst}" && exit 0
			;;
		esac

		reject "Currently only allow merge from vendor/* to main"
	fi
done
